config/routes.rb
Rails.application.routes.draw do
  resources :applicants

  root 'applicants#new'

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  validates :repo, presence: true
  validates :url, presence: true
  validates :bestpract, presence: true
  validates :moddev, presence: true
  validates :fsworkflow, presence: true
  validates :testing, presence: true
  validates :dbknowl, presence: true
  validates :debugging, presence: true
  validates :psolving, presence: true
  validates :javascript, presence: true
  validates :HTML, presence: true
  validates :CSS, presence: true
  validates :team, presence: true
  validates :motivation, presence: true
  validates :communication, presence: true
  validates :energy, presence: true
  validates :intelligence, presence: true

end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy]

  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        ApprenticeMailer.survey_email(@applicant).deliver_now
        format.html { redirect_to @applicant, notice: 'Applicant submission was successful!' }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url, notice: 'Applicant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit(:name, :email, :repo, :url, :bestpract, :moddev, :fsworkflow, :testing, :dbknowl, :debugging, :psolving, :javascript, :HTML, :CSS, :team, :motivation, :communication, :energy, :intelligence)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applicants/_form.html.erb
<%= form_for(@applicant) do |f| %>
  <% if @applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
      <% @applicant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
  <div class="field">
    <%= f.text_field :name, :placeholder => "FULL NAME" %>
  </div><br>
  <div class="field">
    <%= f.text_field :email, :placeholder => "EMAIL" %>
  </div><br>
  <div class="field">
    <%= f.text_field :repo, :placeholder => "PROJECT REPO" %>
  </div><br>
  <div class="field">
    <%= f.text_field :url, :placeholder => "PROJECT URL" %>
  </div><br>
  <div class="skills">
  <div class="field">
    <%= f.label :bestpract, "USING BEST PRACTICES:" %>
    <%= f.number_field :bestpract %>
  </div>
  <div class="field">
    <%= f.label :moddev, "MODULAR DEVELOPMENT:" %>
    <%= f.number_field :moddev %>
  </div>
  <div class="field">
    <%= f.label :fsworkflow, "FUll STACK WORKFLOW UNDERSTANDING:" %>
    <%= f.number_field :fsworkflow %>
  </div>
  <div class="field">
    <%= f.label :testing, "TESTING:" %>
    <%= f.number_field :testing %>
  </div>
  <div class="field">
    <%= f.label :dbknowl, "DATABASE KNOWLEDGE:" %>
    <%= f.number_field :dbknowl %>
  </div>
  <div class="field">
    <%= f.label :debugging, "DEBUGGING:" %>
    <%= f.number_field :debugging %>
  </div>
  <div class="field">
    <%= f.label :psolving, "PROBLEM SOLVING SKILLS:" %>
    <%= f.number_field :psolving %>
  </div>
  <div class="field">
    <%= f.label :javascript, "JAVASCRIPT:" %>
    <%= f.number_field :javascript %>
  </div>
  <div class="field">
    <%= f.label :HTML, "HTML:" %>
    <%= f.number_field :HTML %>
  </div>
  <div class="field">
    <%= f.label :CSS, "CSS:" %>
    <%= f.number_field :CSS %>
  </div>
  <div class="field">
    <%= f.label :team, "WORKING ON A TEAM:" %>
    <%= f.number_field :team %>
  </div>
  <div class="field">
    <%= f.label :motivation, "SELF MOTIVATION:" %>
    <%= f.number_field :motivation %>
  </div>
  <div class="field">
    <%= f.label :communication, "COMMUNICATION SKILLS:" %>
    <%= f.number_field :communication %>
  </div>
  <div class="field">
    <%= f.label :energy, "YOUR OWN ENERGY LEVEL:" %>
    <%= f.number_field :energy %>
  </div>
  <div class="field">
    <%= f.label :intelligence, "INTELLIGENCE:" %>
    <%= f.number_field :intelligence %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit "SUBMIT" %>
  </div>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing Applicant</h1>

<%= render 'form' %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<p id="notice"><%= notice %></p>
<div class="show">
<h1>Listing Applicants</h1>

<table>
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Email</th>
      <th>Project Repo</th>
      <th>Project Url</th>
      <th>Using Best Practices for OOP</th>
      <th>Modular Development</th>
      <th>Full Stack Workflow Understanding</th>
      <th>Testing</th>
      <th>Database knowledge</th>
      <th>Debugging</th>
      <th>Problem Solving Skills</th>
      <th>Javascript</th>
      <th>Html</th>
      <th>Css</th>
      <th>Working on a Team</th>
      <th>Self Motivation</th>
      <th>Communication Skills</th>
      <th>Your Own Energy Level</th>
      <th>Intelligence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applicants.each do |applicant| %>
      <tr>
        <td><%= applicant.name %></td>
        <td><%= applicant.email %></td>
        <td><%= applicant.repo %></td>
        <td><%= applicant.url %></td>
        <td><%= applicant.bestpract %></td>
        <td><%= applicant.moddev %></td>
        <td><%= applicant.fsworkflow %></td>
        <td><%= applicant.testing %></td>
        <td><%= applicant.dbknowl %></td>
        <td><%= applicant.debugging %></td>
        <td><%= applicant.psolving %></td>
        <td><%= applicant.javascript %></td>
        <td><%= applicant.HTML %></td>
        <td><%= applicant.CSS %></td>
        <td><%= applicant.team %></td>
        <td><%= applicant.motivation %></td>
        <td><%= applicant.communication %></td>
        <td><%= applicant.energy %></td>
        <td><%= applicant.intelligence %></td>
        <td><%= link_to 'Show', applicant %></td>
        <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
        <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
</div>

<%= link_to 'New Applicant', new_applicant_path %>

app/views/applicants/new.html.erb
<div class="head">
<h1>Welcome New Applicant!</h1>
<h2>Please fill out the form below. You have a total of 50 points to allocate to your skills.</h2>
</div>

<%= render 'form' %>

app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>
<div class='confirmation'>
<h2> Thank you for your interest in Trim Agency!<h2><br>
<h2>We will be in contact with you soon.<h2>
</div>



<!--
<div class="show">
<p>
  <strong>Full Name:</strong>
  <%= @applicant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @applicant.email %>
</p>

<p>
  <strong>Project Repo:</strong>
  <%= @applicant.repo %>
</p>

<p>
  <strong>Project URL:</strong>
  <%= @applicant.url %>
</p>

<p>
  <strong>Using Best Practices for OOP:</strong>
  <%= @applicant.bestpract %>
</p>

<p>
  <strong>Modular Development:</strong>
  <%= @applicant.moddev %>
</p>

<p>
  <strong>Full Stack Workflow Understanding:</strong>
  <%= @applicant.fsworkflow %>
</p>

<p>
  <strong>Testing:</strong>
  <%= @applicant.testing %>
</p>

<p>
  <strong>Database Knowledge:</strong>
  <%= @applicant.dbknowl %>
</p>

<p>
  <strong>Debugging:</strong>
  <%= @applicant.debugging %>
</p>

<p>
  <strong>Problem Solving Skills:</strong>
  <%= @applicant.psolving %>
</p>

<p>
  <strong>Javascript:</strong>
  <%= @applicant.javascript %>
</p>

<p>
  <strong>HTML:</strong>
  <%= @applicant.HTML %>
</p>

<p>
  <strong>CSS:</strong>
  <%= @applicant.CSS %>
</p>

<p>
  <strong>Working on a Team:</strong>
  <%= @applicant.team %>
</p>

<p>
  <strong>Self Motivation:</strong>
  <%= @applicant.motivation %>
</p>

<p>
  <strong>Communication Skills:</strong>
  <%= @applicant.communication %>
</p>

<p>
  <strong>Your Own Energy Level:</strong>
  <%= @applicant.energy %>
</p>

<p>
  <strong>Intelligence:</strong>
  <%= @applicant.intelligence %>
</p>
</div>

<%= link_to 'Edit', edit_applicant_path(@applicant) %> | -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trimapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>


</body>
</html>